// Auto-generated by set-env.js from .env.pre - DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  urlServer: 'https://gestor.scrum-app.com/api/api/v1',
  apiUrl: 'https://gestor.scrum-app.com/api/api/v1'
};
