// Auto-generated by set-env.js from .env.pro - DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  urlServer: 'https://gestor.scrum-app.com/backend/api',
  apiUrl: 'https://gestor.scrum-app.com/backend/api'
};
