// Auto-generated by set-env.js from .env.local - DO NOT EDIT MANUALLY
export const environment = {
  production: false,
  urlServer: 'http://localhost:3100/api/v1',
  apiUrl: 'http://localhost:3100/api/v1'
};
